### ISSUE TITLE
Authentification ?

### ISSUE THREAD

**Issue by michalss** [sgryphon/essential-logging#2]
Hi i have a huge cluster and i would like to uset his lib to log to elastic directly, but it require auth.  How to do this with this lib pls ?

**Comment by edokan** [comment]
For a workaround I include username and password like https://username:password@elastic.url

**Comment by sgryphon** [comment]
The Elasticsearch logger provider has been moved to the ECS DotNet project.

Find the latest version here:
https://github.com/elastic/ecs-dotnet/blob/master/src/Elasticsearch.Extensions.Logging/ReadMe.md

The nuget package is here:
https://www.nuget.org/packages/Elasticsearch.Extensions.Logging/1.6.0-alpha1

The new package supports a number of different ShipTo destinations, including both username/password and using Cloud API Key.
