### ISSUE TITLE
How to customize writing to Elastic?

### ISSUE THREAD

**Issue by RomanPlekhanov** [sgryphon/essential-logging#4]
Hello! I need customize "_source" section and ignore some sections for write. Can I customize it?
For example I need:

```
{
  "_index": "logstash-2021.12.02-000009",
  "_type": "_doc",
  "_id": "WfcG0Bdc_O05",
  "_version": 1,
  "_score": null,
  "_source": {
    "text": "Some message",
    "@version": "1",
    "@timestamp": "2021-12-14T08:17:34.435Z",
    "source": "Some source",
    "trace_id": "20211214111959",
    "module": "Some module",
    "severity": "info"
  },
  "fields": {
    "@timestamp": [
      "2021-12-14T08:17:34.435Z"
    ]
  },
  "sort": [
    1639469854435
  ]
}
```
However when I write, get result like this:
```
{
  "_index": "logstash-2021.12.02-000009",
  "_type": "_doc",
  "_id": "780c2d87-558c-4385-b2a5-f7fc3ee7f630",
  "_version": 1,
  "_score": null,
  "_source": {
    "MessageTemplate": "{0}: Run worker.",
    "agent": {
      "version": "1.3.2+b2d4e7c",
      "type": "Essential.LoggerProvider.Elasticsearch"
    },
    "ecs": {
      "version": "1.5.0"
    },
    "event": {
      "code": "0",
      "severity": 6
    },
    "log": {
      "level": "Information",
      "logger": "BoxLoaderWorker.Worker"
    },
    "service": {
      "type": "BoxLoaderWorker",
      "version": "1.0.0"
    },
    "@timestamp": "2021-12-14T11:20:55.6731768+03:00",
    "labels": {
      "0": "2021-12-14T11:20:55.659437+03:00"
    },
    "message": "12/14/2021 11:20:55 +03:00: Run worker."
  },
  "fields": {
    "@timestamp": [
      "2021-12-14T08:20:55.673Z"
    ]
  },
  "sort": [
    1639470055673
  ]
}
```

**Comment by sgryphon** [comment]
You can't customise like you want through configuration; but you could derive your own code / logger provider to do it.

This logger specifically follows the Elastic Common Schema (ECS) format, which has a specific format for the message sent to Elasticsearch, e.g. severity is in the field event.severity (and the related log level in log.level). https://www.elastic.co/guide/en/ecs/current/index.html

This means it does not directly support the arbitrary custom format that you want. Sorry.

You would need to fork the code (actually use the new version; see below), and then replace the internal generation with the custom section that you want. The (new) code is available under the Apache-2 licence, so you can use it as a base.

----

Also note that the Elasticsearch logger provider has been moved to the ECS DotNet project.

Find the latest version here:
https://github.com/elastic/ecs-dotnet/blob/master/src/Elasticsearch.Extensions.Logging/ReadMe.md

The nuget package is here:
https://www.nuget.org/packages/Elasticsearch.Extensions.Logging/1.6.0-alpha1
