### ISSUE TITLE
dependency injection not working for Elasticsearch.Extensions.logging

### ISSUE THREAD

**Issue by MalkaGit** [sgryphon/essential-logging#5]
Hello,
i added the nuget package 
and configured the logging 
                .ConfigureLogging(logBuilder =>
                {
                    logBuilder.AddElasticsearch();   ....

However, application fails to start:
System.InvalidOperationException: 
Unable to resolve service for type 'Microsoft.Extensions.Logging.Configuration.ILoggerProviderConfiguration
`1[Elasticsearch.Extensions.Logging.ElasticsearchLoggerProvider]' 
while attempting to activate 'Elasticsearch.Extensions.Logging.ElasticsearchLoggerOptionsSetup'.

 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites
 (ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)

**Comment by sgryphon** [comment]
Hi. The Elasticsearch logger was (happily) taken up by Elasticsearch, and moved into their official Elastic repository, https://github.com/elastic/ecs-dotnet/tree/main/src/Elastic.Extensions.Logging

The latest version of the project readme is here: https://github.com/elastic/ecs-dotnet/blob/main/src/Elastic.Extensions.Logging/README.md

So, it may be best to log the issue there.

But, a few questions (cut and paste this to the Elastic project if you want):
* Can you confirm the specific version of .NET you are using, the operating system, and tools (e.g. IDE) you are using. I haven't tested the library for a while (I mostly use OpenTelemetry these days), so not sure how it works with .NET 8. It looks like a missing dependency registration (the code was probably assuming it was registered by default, but maybe some of the defaults changed and you now need to register it manually).
* Can you check if the example project works: https://github.com/elastic/ecs-dotnet/tree/main/examples/console-with-extensions-logging
* Make sure you are using the latest version of the library, from here: https://www.nuget.org/packages/Elasticsearch.Extensions.Logging/8.4.0-alpha4

**Comment by MalkaGit** [comment]
Hello,
Thank you for your replay.
Our projects are working with log4net (appenders).
We want write to elastic using log4net appender,
The question is ,is there log4net appender that writes to elastic search efficiently ? (bulk, async etc)

**Comment by sgryphon** [comment]
>Our projects are working with log4net (appenders).

This project / Elastic.Extensions.Logging is for standard Microsoft.Extensions.Logging.

However the ECS Dotnet project has components for all major logging systems, including log4net. See https://github.com/elastic/ecs-dotnet/tree/main

There is a layout (doesn't look like an appender though) in Elastic.CommonSchema.Log4net -- I haven't used Log4net for a long time, and have not been involved in that part of the project.

These days I would also look at OpenTelemetry as a standardised protocol for any logging needs. Elastic APM now supports OTel, although I think log4net is quite old and does not appear to have a lot of activity or any OTel appender. 

With the ECS layout either write to console appender, if you are running in a container that is capturing console output, or you may have to append to a file then injest that into Elastic. Best of luck (and look at OTel as an alternative)
